### ISSUE TITLE
Switch to YAML

### ISSUE THREAD

**Issue by Arcterus** [mesalock-linux/packages#4]
We should switch from PKGBUILD-like shell scripts to a custom YAML format like so (this is for glibc):
```yaml
env:
  name: glibc
  ver: 2.26
  patch: 0

package:
  name: $name
  version: $ver.$patch
  description: Glibc
  license:
    - GPL
    - LGPL

  source:
    - http://ftp.gnu.org/gnu/$name/$name-$ver.tar.gz

  build:
    - |
      echo "slibdir=/usr/lib" >> configparms
      echo "rtlddir=/usr/lib" >> configparms
      echo "sbindir=/usr/bin" >> configparms
      echo "rootsbindir=/usr/bin" >> configparms
    - $name-$ver/configure
          --prefix=/usr
          --libdir=/usr/lib
          --libexecdir=/usr/lib
          --enable-add-ons
          --enable-bind-now
          --disable-profile
          --enable-stackguard-randomization
          --enable-stack-protector=strong
          --enable-lock-elision
          --enable-multi-arch
          --disable-werror

      # build libraries with fortify disabled
    - echo "build-programs=no" >> configparms
    - make

      # re-enable fortify for programs
    - sed -i "/build-programs=/s#no#yes#" configparms

    - |
      echo "CC += -D_FORTIFY_SOURCE=2" >> configparms
      echo "CXX += -D_FORTIFY_SOURCE=2" >> configparms
    - make

  install:
      # mkdir -p install-root
      # make install_root=$(pwd)/install-root install
    - make install_root="$pkgdir" install
    - strip --strip-unneeded "$pkgdir"/usr/lib/{libdl.so.2,libm.so.6,librt.so.1}
```
